### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by JuChanMin** [Guillaume351/Skywars_Nukkit#3]
When I joined the server...

> 2020-08-12 01:43:55.533 [main] FATAL - Could not pass event "cn.nukkit.event.player.PlayerItemHeldEvent" to "SkyWars v1.0.0": null on Skywars.Main
2020-08-12 01:43:55.534 [main] ERROR - Throwing
cn.nukkit.utils.EventException: null
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:543) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.inventory.PlayerInventory.equipItem(PlayerInventory.java:65) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2415) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_241]
	at cn.nukkit.network.Network.processPackets(Network.java:268) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.Network.processBatch(Network.java:251) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Player.handleDataPacket(Player.java:2102) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:156) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.network.Network.processInterfaces(Network.java:152) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tick(Server.java:1137) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.tickProcessor(Server.java:916) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.start(Server.java:893) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:578) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.Error: 분석되지 않는 컴파일 문제점: 
	AllServersScreen을(를) 유형으로 분석할 수 없습니다.
	at Skywars.Main.onItemHeldEvent(Main.java:103) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]
	... 17 more

Caused by: java.lang.Error: 분석되지 않는 컴파일 문제점 = Caused by: java.lang.Error: Compile issues that are not analyzed:
	AllServersScreen을(를) 유형으로 분석할 수 없습니다. = AllServerScreen could not be analyzed as a type.

I used skywars plugin only.

I still didn't know what was wrong with me...
Can you help me? :c

**Comment by Guillaume351** [comment]
Hello,
Sorry for the delay.
Did you have items on your inventory ?
Try disabling player data saving in nukkit.yml and delete players folder. I will try to add instruction to avoid this issue

**Comment by JuChanMin** [comment]
I saw it too late Sorry.. :c

And thanks for answering :)
